import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import QueryProvider from "./QueryProvider";

const space_Grotesk = Montserrat({
  subsets: ["latin", "latin-ext"],
  weight: ["400", "700", "300", "900"],
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${space_Grotesk.className} ${space_Grotesk.variable}  antialiased pt-[120px] bg-[#f5f5f5]`}
      >
        <QueryProvider>
          <Header />
          {children}

          <Footer />
          <ToastContainer />
        </QueryProvider>
      </body>
    </html>
  );
}
